config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resource :session, only: [:new, :create, :destroy]
  
  root to: 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: {only_integer: true}
  validates :description, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_past

  mount_uploader :poster, PosterUploader

  def review_average
    if reviews.size != 0
      reviews.sum(:rating_out_of_ten)/reviews.size
    else
      0
    end
  end

  protected

  def release_date_is_in_the_past
    if release_date.present? 
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

  def self.search_title_director(search_term)
    where("title LIKE :term OR director LIKE :term", term: "%#{search_term}%")
  end

  def self.search_time(search_term)
    case search_term
    when '1' then where("runtime_in_minutes <= ?", 90)
    when '2' then where("runtime_in_minutes > ? AND runtime_in_minutes <= ?", 90, 120)
    when '3' then where("runtime_in_minutes > ?", 120)
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: {
              only_integer: true, 
              greater_than_or_equal_to: 1, 
              less_than_or_equal_to: 10
            }
end

app/models/user.rb
class User < ActiveRecord::Base

  after_destroy :send_email

  has_many :reviews, dependent: :destroy
  has_secure_password

  paginates_per 10

  def full_name
    "#{firstname} #{lastname}"
  end

  def send_email
    UserMailer.delete_email(self).deliver
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :authorize_user

  def index
    @users = User.all.page(params[:page])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy

    head :no_content
  end

  protected

  def authorize_user
    unless current_user.admin?
      flash[:notice] = "You need to be an admin to access that page"
      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movie = Movie.all

    if params[:title_or_director]
      @movie = @movie.search_title_director(params[:title_or_director]) 
    end
    
    if params[:runtime_in_minutes]
      @movie = @movie.search_time(params[:runtime_in_minutes])
    end

  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster, :description, :remote_poster_url
    )
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Goodbye!"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      UserMailer.welcome_email(@user).deliver
      redirect_to movies_path, notice: "Welcome, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1>Banana Members</h1>

<%= paginate @users %>

<hr>
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Date Joined</th>
    <th>Admin?</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.firstname %></td>
      <td><%= user.lastname %></td>
      <td><%= user.email %></td>
      <td><%= formatted_date(user.created_at) %></td>
      <td><%= user.admin %></td>
    </tr>
  <% end %>
</table>
<hr>

app/views/layouts/_footer.html.erb
<footer> 
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)

      <% if current_user.admin %>
        <%= link_to "Admin Page", admin_users_path %>
      <% end %>

    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PerishedBananas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>

</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted: 
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :poster %><br>
    <%= f.file_field :poster %>
  </div>
  <div>
    <%= f.label :remote_poster_url %><br>
    <%= f.text_field :remote_poster_url %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<%= link_to image_tag(m.poster.thumb), movie_path(m) %>
<h1><%= link_to m.title, movie_path(m) %></h1>
<h1>Average score: <%= m.review_average %></h1>
<h4> Directed by <%= m.director %> | <%= m.runtime_in_minutes %> minutes | Released <%= formatted_date(m.release_date) %></h4>
<p><%= m.description %></p>
<hr>

app/views/movies/_search.html.erb
<%= form_tag('/movies', method: "get") do %>
  <div>
    <%= label_tag :title_or_director, "Search by a movie's title or director" %><br>
    <%= text_field_tag :title_or_director %>
  </div>
  <div>
    <%= label_tag :runtime_in_minutes %><br>
    <%= select_tag :runtime_in_minutes, options_for_select([
      ["All", ""], 
      ["Under 1.5 hours", 1], 
      ["1.5 - 2 hours",   2], 
      ["Over 2 hours",    3]
    ]) %>
  </div>
  <div>
    <%= submit_tag "Search", name: 'search' %>
    <%= submit_tag "Clear", type: 'reset' %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>
<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Perished Bananas</h1>

<%= link_to "Submit a movie!", new_movie_path %>
<hr>
<h2>Search for a movie:</h2>
<%= render 'search' %>
<hr>
<%= render :partial => "movie", :collection => @movie, :as => :m %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>
<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.poster.thumb), movie_path(@movie) %>
<h2><%= @movie.title %> (<%=link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "Are you sure?" %>)</h2>
<h1>Average score: <%= @movie.review_average %></h1>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Directed by <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes </h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %> 

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented this user from being created: 
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>